services:
  - type: web
    name: wordpress
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: WORDPRESS_DB_HOST
        sync: false
      - key: WORDPRESS_DB_USER
        sync: false
      - key: WORDPRESS_DB_PASSWORD
        sync: false
      - key: WORDPRESS_DB_NAME
        sync: false
      - key: WORDPRESS_TABLE_PREFIX
        value: "wp_"
      - key: WORDPRESS_DEBUG
        value: "1"
      - key: WORDPRESS_CONFIG_EXTRA
        value: "define('WP_HOME', 'https://' . $_SERVER['HTTP_HOST']); define('WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST']);" 